version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      
  pre_build:
    commands:
      - echo "executing pre build"
      - echo "establish connection with ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 477827136140.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - mvn package
      - echo "Building docker image"
      - docker build -t article_get_function .
      - docker tag article_get_function:latest 477827136140.dkr.ecr.us-east-1.amazonaws.com/article_get_function:latest
      - docker push 477827136140.dkr.ecr.us-east-1.amazonaws.com/article_get_function:latest
  post_build:
    commands:
      - printf '[{"name":"container_name","imageUri":"image_URI"}]' > imagedefinitions.json
      - echo "Application Built successfully"
artifacts:
    files: imagedefinitions.json